alter session set "_ORACLE_SCRIPT"=true; 

CREATE ROLE ROLE_NHANVIEN;
CREATE ROLE ROLE_QLTT;
CREATE ROLE ROLE_TRUONGPHONG;
CREATE ROLE ROLE_TAICHINH;
CREATE ROLE ROLE_NHANSU;
CREATE ROLE ROLE_TRUONGDA;
CREATE ROLE ROLE_BGD;