alter session set "_ORACLE_SCRIPT"=true; 

--DROP ROLE ROLE_NHANVIEN;
--DROP ROLE ROLE_QLTT;
--DROP ROLE ROLE_TRUONGPHONG;
--DROP ROLE ROLE_TAICHINH;
--DROP ROLE ROLE_NHANSU;
--DROP ROLE ROLE_TRUONGDA;
--DROP ROLE ROLE_BGD;

CREATE ROLE ROLE_NHANVIEN;
CREATE ROLE ROLE_QLTT;
CREATE ROLE ROLE_TRUONGPHONG;
CREATE ROLE ROLE_TAICHINH;
CREATE ROLE ROLE_NHANSU;
CREATE ROLE ROLE_TRUONGDA;
CREATE ROLE ROLE_BGD;

--TC1
CREATE OR REPLACE VIEW NV_SELECT_NHANVIEN AS
SELECT * 
FROM NHANVIEN 
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
WITH CHECK OPTION;

CREATE OR REPLACE VIEW NV_SELECT_PHANCONG AS
SELECT PC.*
FROM PHANCONG PC, NHANVIEN NV
WHERE PC.MANV = NV.MANV AND NV.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
WITH CHECK OPTION;

CREATE OR REPLACE VIEW NV_UPDATE_NHANVIEN AS
SELECT NGAYSINH, DIACHI, SODT 
FROM NHANVIEN 
WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
WITH CHECK OPTION;


GRANT SELECT ON NV_SELECT_NHANVIEN TO ROLE_NHANVIEN;
GRANT SELECT ON NV_SELECT_PHANCONG TO ROLE_NHANVIEN;
GRANT UPDATE ON NV_UPDATE_NHANVIEN TO ROLE_NHANVIEN;
--GRANT EXECUTE ON PROC_NV_UPDATE_NHANVIEN TO ROLE_NHANVIEN;

GRANT SELECT ON PHONGBAN TO ROLE_NHANVIEN;
GRANT SELECT ON DEAN TO ROLE_NHANVIEN;


--TC2
CREATE OR REPLACE VIEW QLTT_SELECT_NHANVIEN AS
SELECT DISTINCT NV.MANV, NV.TENNV, NV.PHAI, NV.NGAYSINH, NV.DIACHI, NV.SODT, NV.VAITRO, NV.MANQL, NV.PHG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),LUONG) LUONG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),PHUCAP) PHUCAP
FROM NHANVIEN NV
WHERE NV.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
UNION
SELECT DISTINCT NV2.MANV, NV2.TENNV, NV2.PHAI, NV2.NGAYSINH, NV2.DIACHI, NV2.SODT, NV2.VAITRO, NV2.MANQL, NV2.PHG,
DECODE(NV2.USERNAME, NULL, NV2.LUONG) LUONG,
DECODE(NV2.USERNAME, NULL, NV2.PHUCAP) PHUCAP
FROM NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER') AND NV2.MANQL = NV1.MANV AND NV1.MANV != NV2.MANV
AND NV2.VAITRO = 1
WITH CHECK OPTION;


CREATE OR REPLACE VIEW QLTT_SELECT_PHANCONG AS
SELECT PC.* 
FROM PHANCONG PC, NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER') 
AND (NV1.MANV = PC.MANV OR (NV1.MANV = NV2.MANQL AND NV2.MANV = PC.MANV))
WITH CHECK OPTION;

GRANT ROLE_NHANVIEN TO ROLE_QLTT;
GRANT SELECT ON QLTT_SELECT_NHANVIEN TO ROLE_QLTT;
GRANT SELECT ON QLTT_SELECT_PHANCONG TO ROLE_QLTT;


--TC3

CREATE OR REPLACE VIEW TP_SELECT_NHANVIEN AS
SELECT DISTINCT NV.MANV, NV.TENNV, NV.PHAI, NV.NGAYSINH, NV.DIACHI, NV.SODT, NV.VAITRO, NV.MANQL, NV.PHG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),LUONG) LUONG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),PHUCAP) PHUCAP
FROM NHANVIEN NV
WHERE NV.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
UNION
SELECT DISTINCT NV2.MANV, NV2.TENNV, NV2.PHAI, NV2.NGAYSINH, NV2.DIACHI, NV2.SODT, NV2.VAITRO, NV2.MANQL, NV2.PHG,
DECODE(NV2.USERNAME, NULL, NV2.LUONG) LUONG,
DECODE(NV2.USERNAME, NULL, NV2.PHUCAP) PHUCAP
FROM NHANVIEN NV1, NHANVIEN NV2, PHONGBAN PB
WHERE NV1.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER') 
AND NV1.MANV = PB.TRPHG AND NV2.PHG = PB.MAPB AND NV2.MANV <> NV1.MANV
WITH CHECK OPTION;


CREATE OR REPLACE VIEW TP_UPDATE_PHANCONG AS
SELECT PC.*
FROM PHANCONG PC, NHANVIEN NV1, NHANVIEN NV2, PHONGBAN PB
WHERE NV1.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
AND NV1.MANV = PB.TRPHG AND NV2.PHG = PB.MAPB AND NV2.MANV <> NV1.MANV
AND PC.MANV = NV2.MANV
WITH CHECK OPTION;


CREATE OR REPLACE TRIGGER TP_UPDATE_PHANCONG1
INSTEAD OF insert on TP_UPDATE_PHANCONG
for each row
BEGIN
 INSERT INTO U_AD.PHANCONG(MANV,MADA,THOIGIAN) values(:new.MANV,:new.MADA,:new.THOIGIAN);
END;

CREATE OR REPLACE TRIGGER TP_UPDATE_PHANCONG2
INSTEAD OF DELETE on TP_UPDATE_PHANCONG
for each row
BEGIN
    DELETE FROM U_AD.PHANCONG WHERE MANV = :old.MANV AND MADA = :old.MADA;
END;


GRANT SELECT ON TP_SELECT_NHANVIEN TO ROLE_TRUONGPHONG;
GRANT SELECT, INSERT, UPDATE, DELETE ON TP_UPDATE_PHANCONG TO ROLE_TRUONGPHONG;
GRANT UPDATE ON U_AD.PHANCONG TO ROLE_TRUONGPHONG;

GRANT ROLE_NHANVIEN TO ROLE_TRUONGPHONG;


--TC4
CREATE OR REPLACE VIEW TC_UPDATE_NHANVIEN AS
SELECT MANV, LUONG, PHUCAP
FROM NHANVIEN
WITH CHECK OPTION;

GRANT ROLE_NHANVIEN TO ROLE_TAICHINH;
GRANT SELECT, UPDATE ON TC_UPDATE_NHANVIEN TO ROLE_TAICHINH;
GRANT SELECT,UPDATE ON NHANVIEN TO ROLE_TAICHINH;
GRANT SELECT ON PHANCONG TO ROLE_TAICHINH;


--TC5
CREATE OR REPLACE VIEW NS_SELECT_NHANVIEN AS
SELECT DISTINCT NV.MANV, NV.TENNV, NV.PHAI, NV.NGAYSINH, NV.DIACHI, NV.SODT, NV.VAITRO, NV.MANQL, NV.PHG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),LUONG) LUONG,
DECODE(NV.USERNAME,SYS_CONTEXT('USERENV', 'SESSION_USER'),PHUCAP) PHUCAP
FROM NHANVIEN NV
WHERE NV.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
UNION
SELECT DISTINCT NV2.MANV, NV2.TENNV, NV2.PHAI, NV2.NGAYSINH, NV2.DIACHI, NV2.SODT, NV2.VAITRO, NV2.MANQL, NV2.PHG,
DECODE(NV2.USERNAME, NULL, NV2.LUONG) LUONG,
DECODE(NV2.USERNAME, NULL, NV2.PHUCAP) PHUCAP
FROM NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER') AND NV2.MANV != NV1.MANV
WITH CHECK OPTION;

CREATE OR REPLACE VIEW NS_UPDATE_NHANVIEN
AS
    SELECT MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, PHG, USERNAME FROM NHANVIEN;
    
CREATE OR REPLACE TRIGGER NS_INSERT_NHANVIEN
INSTEAD OF insert on NS_UPDATE_NHANVIEN
for each row
BEGIN
 INSERT INTO U_AD.NHANVIEN(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,LUONG,PHUCAP, VAITRO, MANQL, PHG, USERNAME) 
 values(:NEW.MANV, :NEW.TENNV, :NEW.PHAI, :NEW.NGAYSINH, :NEW.DIACHI, :NEW.SODT,NULL,NULL, :NEW.VAITRO, :NEW.MANQL, :NEW.PHG, :NEW.USERNAME);
END;

GRANT SELECT ON NS_SELECT_NHANVIEN TO ROLE_NHANSU;
GRANT DELETE,INSERT, UPDATE ON NS_UPDATE_NHANVIEN TO ROLE_NHANSU;
GRANT ROLE_NHANVIEN TO ROLE_NHANSU;
GRANT SELECT, INSERT, UPDATE ON U_AD.PHONGBAN TO ROLE_NHANSU;


--TC6
GRANT ROLE_NHANVIEN TO ROLE_TRUONGDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON DEAN TO ROLE_TRUONGDA;

--ROLE_BGD
GRANT SELECT ON NHANVIEN TO ROLE_BGD;
GRANT SELECT ON PHONGBAN TO ROLE_BGD;
GRANT SELECT ON DEAN TO ROLE_BGD;
GRANT SELECT ON PHANCONG TO ROLE_BGD;