alter session set "_ORACLE_SCRIPT"=true; 
--DROP USER U_AD CASCADE;
CREATE USER U_AD IDENTIFIED BY 0;

GRANT ALL PRIVILEGES TO U_AD with ADMIN OPTION;

GRANT SELECT ON DBA_TAB_PRIVS TO U_AD WITH GRANT OPTION;
GRANT SELECT ON ROLE_TAB_PRIVS TO U_AD WITH GRANT OPTION;

GRANT SELECT ON dba_tables to U_AD WITH GRANT OPTION;

GRANT SELECT ON dba_users to U_AD WITH GRANT OPTION;

GRANT SELECT ON USER_ROLE_PRIVS to U_AD WITH GRANT OPTION;
GRANT SELECT ON DBA_ROLES to U_AD WITH GRANT OPTION;

grant execute on DBMS_RLS to U_AD;
grant execute on DBMS_CRYPTO to U_AD;

GRANT SELECT ON dba_audit_trail TO U_AD;

GRANT SELECT ON dba_audit_trail TO U_AD;
GRANT EXECUTE ON DBMS_FGA TO U_AD;
GRANT SELECT ON SYS.FGA_LOG$ TO U_AD;


--U_AD
DROP USER U_TEST1;
CREATE USER U_TEST1 IDENTIFIED BY 0;
GRANT CONNECT, RESOURCE TO U_TEST1;
GRANT SELECT ON DBA_TAB_PRIVS TO U_TEST1;
GRANT SELECT ON DBA_TABLES TO U_TEST1;
GRANT SELECT ON DBA_USERS TO U_TEST1;

--DROP ROLE
DROP ROLE R_ROLE1;
DROP ROLE R_ROLE2;

--CREATE ROLES
CREATE ROLE R_ROLE1;
CREATE ROLE R_ROLE2;

--
GRANT R_ROLE1 TO U_TEST1;

GRANT SELECT ON U_AD.EMP_20127480 TO R_ROLE1;
GRANT SELECT ON U_AD.DEPT_20127480 TO R_ROLE1;