
SELECT * FROM DBA_TAB_PRIVS;
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;
SELECT * FROM dba_sys_privs;
SELECT * FROM ROLE_TAB_PRIVS;
SELECT *
FROM dba_tab_privs;

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'U_AD' AND TYPE = 'TABLE' ORDER BY TABLE_NAME;

--tc1
alter session set "_ORACLE_SCRIPT"=true;

create user NV227 identified by 0;
GRANT CREATE SESSION TO NV227;

grant ROLE_NHANVIEN to NV227;

select * from U_AD.NV_SELECT_NHANVIEN;
select * from U_AD.NV_SELECT_PHANCONG;
update U_AD.NV_UPDATE_NHANVIEN set DIACHI = 'ADU';
COMMIT;
select * from U_AD.PHONGBAN;
select * from U_AD.DEAN;

--EXECUTE U_AD.PROC_NV_UPDATE_NHANVIEN('VCL','','',1);
SELECT * FROM NHANVIEN WHERE MANV= 'NV227';


--tc2
alter session set "_ORACLE_SCRIPT"=true;

create user QL417 identified by 0;
GRANT CREATE SESSION TO QL417;

grant ROLE_QLTT to QL417;

select * from U_AD.QLTT_SELECT_NHANVIEN;
select * from U_AD.QLTT_SELECT_PHANCONG;

--tc3
alter session set "_ORACLE_SCRIPT"=true;

create user TP421 identified by 0;
GRANT CREATE SESSION TO TP421;

grant ROLE_TRUONGPHONG to TP421;

select * from U_AD.TP_SELECT_NHANVIEN;
select * from U_AD.TP_VIEW_PHANCONG;
select * from U_AD.TP_UPDATE_PHANCONG;
insert into U_AD.TP_UPDATE_PHANCONG values ('NV001','DA93',TO_DATE('11/11/11','MM/DD/YY')) COMMIT;

delete
from U_AD.TP_UPDATE_PHANCONG
where MANV = 'NV001' AND MADA ='DA93' COMMIT;

update U_AD.TP_UPDATE_PHANCONG set THOIGIAN = TO_DATE('11/11/99','MM/DD/YY') WHERE MANV ='NV354' and MADA = 'DA39';

delete
from U_AD.PHANCONG
where MANV = 'NV001' AND MADA ='DA93';

SELECT * FROM PHANCONG WHERE MANV = 'NV001' AND MADA = 'DA93';


--TC4
alter session set "_ORACLE_SCRIPT"=true;

create user TC452 identified by 0;
GRANT CREATE SESSION TO TC452;
grant ROLE_TAICHINH to TC452;

SELECT * FROM U_AD.NHANVIEN WHERE MANV = 'NV227';
SELECT * FROM U_AD.PHANCONG;

UPDATE U_AD.TC_UPDATE_NHANVIEN
SET LUONG = 3200
WHERE MANV = 'NV227';
COMMIT;

UPDATE U_AD.TC_UPDATE_NHANVIEN
SET PHUCAP = 3200
WHERE MANV = 'NV227';

select * from U_AD.NHANVIEN WHERE MANV ='NV227';

--tc5
alter session set "_ORACLE_SCRIPT"=true;

create user NS492 identified by 0;
GRANT CREATE SESSION TO NS492;
grant ROLE_NHANSU to NS492;

INSERT INTO U_AD.NS_UPDATE_NHANVIEN 
VALUES ('QL777', N'Akane', N'Nu', TO_DATE('11/11/99','MM/DD/YY'), N'Golden Square', '0966264344', 2,NULL, 'PB05', 'QL777');
COMMIT;

INSERT INTO U_AD.NS_UPDATE_NHANVIEN (MANV)
VALUES('NV789');
commit;

UPDATE U_AD.NS_UPDATE_NHANVIEN SET TENNV = 'hellO' WHERE MANV='NV789';
commit;

delete from U_AD.NS_UPDATE_NHANVIEN where MANV = 'QL777';
COMMIT;

INSERT INTO U_AD.PHONGBAN(MAPB, TENPB, TRPHG) VALUES ('PB09', 'HR', 'TP423');

select * from U_AD.PHONGBAN where MAPB = 'PB969'
--tc6
alter session set "_ORACLE_SCRIPT"=true;

create user TDA501 identified by 0;
GRANT CREATE SESSION TO TDA501;
grant ROLE_TRUONGDA to TDA501;

SELECT * FROM U_AD.DEAN;

INSERT INTO U_AD.DEAN(MADA) VALUES ('DA099'); -- them dean
INSERT INTO U_AD.DEAN(MADA, TENDA, NGAYBD, PHONG) VALUES ('DA001', 'Name_DA001', '18-12-2006', 'PB02'); -- them dean
UPDATE U_AD.DEAN SET NGAYBD = TO_DATE('11/18/15','MM/DD/YY') WHERE MADA = 'DA099';commit; -- cap nhat dean
DELETE FROM U_AD.DEAN WHERE MADA = 'DA099';commit; -- xoa dean

--BGD
alter session set "_ORACLE_SCRIPT"=true;

create user BGD01 identified by 0;
GRANT CREATE SESSION TO BGD01;
grant ROLE_BGD to BGD01;

select * from U_AD.NHANVIEN;
--OLS
select * from U_AD.THONGBAO;


--------------------STANDARD AUDIT TESTING--------------------
--B1: dang nhap bang user THANHTRA_6 (khac U_AD la duoc) va chay cau lenh sau:

-- B2: dang nhap bang U_AD, chay cau lenh sau de xem ket qua audit:
select username, EXTENDED_TIMESTAMP ,obj_name, action_name, sql_text 
from dba_audit_trail
WHERE OBJ_NAME = 'NHANVIEN';

--FG Audit
--a
SELECT * FROM PHANCONG;
UPDATE PHANCONG
SET THOIGIAN = '09-NOV-06'
WHERE MANV='NV018';

--b (user BGD)
SELECT * FROM U_AD.NHANVIEN;

--c (user U_AD, TC)
update U_AD.NHANVIEN set LUONG = 1234 where MANV = 'NV061'; COMMIT;
SELECT DBUID, LSQLTEXT, NTIMESTAMP# FROM SYS.FGA_LOG$;



